### ISSUE TITLE
Craft 5 compatibility?

### ISSUE THREAD

**Issue by amici-infotech** [lindseydiloreto/craft-inventory#24] opened 2024-03-29 12:22 UTC
Hey, As Craft 5 is officially launched. Could you consider making this plugin upgrade to craft 5 please?

**Comment by lindseydiloreto** [comment] 2024-03-29 17:49
Duplicate of #23 

Short answer is no, because the plugin is no longer necessary in Craft 5.

**Closed as completed by lindseydiloreto** 2024-03-29 17:49 UTC
