### ISSUE TITLE
[BUG] PHP Notice after removing global set (unable to view the inventory panel)

### ISSUE THREAD

**Issue by Antimated** [lindseydiloreto/craft-inventory#16] opened 2021-12-16 09:38 UTC
After I removed a global set I am now unable to view the `craft/inventory/fields` panel.

![Screenshot 2021-12-16 at 10 34 08](https://user-images.githubusercontent.com/2869409/146346136-8e4f8cc6-5412-4292-94eb-ea2218e66221.png)

**Used versions**
Craft: Craft Pro 3.7.26
Inventory: 2.1.1

**Comment by lindseydiloreto** [comment] 2023-03-04 03:37
I know this thread is a bit old, sorry for the delay. I've just tried this with a Craft 4 site, and I'm unable to reproduce the problem.

When I delete a Global Set, I can (correctly) see that it was recently deleted...

<img width="819" alt="Global set deleted" src="https://user-images.githubusercontent.com/5309692/222873793-b845d142-3d61-4347-9b8c-9538f4a3b7f7.png">

Can you (or anyone) still reproduce this issue? If it's no longer reproducible, we may just close this thread.

**Comment by lindseydiloreto** [comment] 2023-04-24 23:52
I'm fairly confident these tickets describe the same bug... in which case, it's been fixed in [v3.0.0](https://github.com/doublesecretagency/craft-inventory/releases/tag/3.0.0)! 🎈

**Closed as completed by lindseydiloreto** 2023-04-24 23:52 UTC
